-- ============================================================
-- ETL: ODS → DWD 创意层小时明细
-- 源表: ods_xhs_creative_report_hi
-- 目标表: dwd_xhs_creative_hourly_di
-- ============================================================

INSERT OVERWRITE TABLE dwd_xhs_creative_hourly_di PARTITION (ds='${bizdate}')
SELECT
    advertiser_id,
    GET_JSON_OBJECT(raw_data, '$.note_id')                          AS note_id,
    GET_JSON_OBJECT(raw_data, '$.unit_id')                          AS unit_id,
    GET_JSON_OBJECT(raw_data, '$.campaign_id')                      AS campaign_id,
    GET_JSON_OBJECT(raw_data, '$.creativity_id')                    AS creativity_id,
    CAST(GET_JSON_OBJECT(raw_data, '$.placement') AS INT)           AS placement,
    CAST(GET_JSON_OBJECT(raw_data, '$.marketing_target') AS INT)    AS marketing_target,
    CAST(GET_JSON_OBJECT(raw_data, '$.promotion_target') AS INT)    AS promotion_target,
    CAST(GET_JSON_OBJECT(raw_data, '$.optimize_target') AS INT)     AS optimize_target,
    CAST(GET_JSON_OBJECT(raw_data, '$.bidding_strategy') AS INT)    AS bidding_strategy,
    GET_JSON_OBJECT(raw_data, '$.dt')                               AS dt,
    CAST(GET_JSON_OBJECT(raw_data, '$.fee') AS DECIMAL(18,2))       AS fee,
    CAST(GET_JSON_OBJECT(raw_data, '$.impression') AS BIGINT)       AS impression,
    CAST(GET_JSON_OBJECT(raw_data, '$.click') AS BIGINT)            AS click,
    CAST(GET_JSON_OBJECT(raw_data, '$.like') AS BIGINT)             AS `like`,
    CAST(GET_JSON_OBJECT(raw_data, '$.comment') AS BIGINT)          AS `comment`,
    CAST(GET_JSON_OBJECT(raw_data, '$.collect') AS BIGINT)          AS collect,
    CAST(GET_JSON_OBJECT(raw_data, '$.follow') AS BIGINT)           AS follow,
    CAST(GET_JSON_OBJECT(raw_data, '$.share') AS BIGINT)            AS share,
    CAST(GET_JSON_OBJECT(raw_data, '$.interaction') AS BIGINT)      AS interaction,
    CAST(GET_JSON_OBJECT(raw_data, '$.action_button_click') AS BIGINT)          AS action_button_click,
    CAST(GET_JSON_OBJECT(raw_data, '$.screenshot') AS BIGINT)                   AS screenshot,
    CAST(GET_JSON_OBJECT(raw_data, '$.pic_save') AS BIGINT)                     AS pic_save,
    CAST(GET_JSON_OBJECT(raw_data, '$.reserve_pv') AS BIGINT)                   AS reserve_pv,
    CAST(GET_JSON_OBJECT(raw_data, '$.video_play_5s_cnt') AS BIGINT)            AS video_play_5s_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.search_cmt_click') AS BIGINT)             AS search_cmt_click,
    CAST(GET_JSON_OBJECT(raw_data, '$.search_cmt_after_read') AS BIGINT)        AS search_cmt_after_read,
    CAST(GET_JSON_OBJECT(raw_data, '$.i_user_num') AS BIGINT)                   AS i_user_num,
    CAST(GET_JSON_OBJECT(raw_data, '$.ti_user_num') AS BIGINT)                  AS ti_user_num,
    CAST(GET_JSON_OBJECT(raw_data, '$.leads') AS BIGINT)                        AS leads,
    CAST(GET_JSON_OBJECT(raw_data, '$.landing_page_visit') AS BIGINT)           AS landing_page_visit,
    CAST(GET_JSON_OBJECT(raw_data, '$.leads_button_impression') AS BIGINT)      AS leads_button_impression,
    CAST(GET_JSON_OBJECT(raw_data, '$.message_user') AS BIGINT)                 AS message_user,
    CAST(GET_JSON_OBJECT(raw_data, '$.message') AS BIGINT)                      AS message,
    CAST(GET_JSON_OBJECT(raw_data, '$.message_consult') AS BIGINT)              AS message_consult,
    CAST(GET_JSON_OBJECT(raw_data, '$.initiative_message') AS BIGINT)           AS initiative_message,
    CAST(GET_JSON_OBJECT(raw_data, '$.msg_leads_num') AS BIGINT)                AS msg_leads_num,
    CAST(GET_JSON_OBJECT(raw_data, '$.invoke_app_open_cnt') AS BIGINT)          AS invoke_app_open_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.invoke_app_enter_store_cnt') AS BIGINT)   AS invoke_app_enter_store_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.invoke_app_engagement_cnt') AS BIGINT)    AS invoke_app_engagement_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.invoke_app_payment_cnt') AS BIGINT)       AS invoke_app_payment_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.search_invoke_button_click_cnt') AS BIGINT) AS search_invoke_button_click_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.invoke_app_payment_amount') AS DECIMAL(18,2)) AS invoke_app_payment_amount,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_activate_cnt') AS BIGINT)             AS app_activate_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_register_cnt') AS BIGINT)             AS app_register_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.first_app_pay_cnt') AS BIGINT)            AS first_app_pay_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.current_app_pay_cnt') AS BIGINT)          AS current_app_pay_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_key_action_cnt') AS BIGINT)           AS app_key_action_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_pay_cnt_7d') AS BIGINT)               AS app_pay_cnt_7d,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_pay_amount') AS DECIMAL(18,2))        AS app_pay_amount,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_activate_amount_1d') AS DECIMAL(18,2)) AS app_activate_amount_1d,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_activate_amount_3d') AS DECIMAL(18,2)) AS app_activate_amount_3d,
    CAST(GET_JSON_OBJECT(raw_data, '$.app_activate_amount_7d') AS DECIMAL(18,2)) AS app_activate_amount_7d,
    CAST(GET_JSON_OBJECT(raw_data, '$.retention_1d_cnt') AS BIGINT)             AS retention_1d_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.retention_3d_cnt') AS BIGINT)             AS retention_3d_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.retention_7d_cnt') AS BIGINT)             AS retention_7d_cnt,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_visit_7') AS BIGINT)       AS external_goods_visit_7,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_order_7') AS BIGINT)       AS external_goods_order_7,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_rgmv_7') AS DECIMAL(18,2))       AS external_rgmv_7,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_order_15') AS BIGINT)      AS external_goods_order_15,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_rgmv_15') AS DECIMAL(18,2))      AS external_rgmv_15,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_order_price_15') AS DECIMAL(18,2)) AS external_goods_order_price_15,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_order_30') AS BIGINT)      AS external_goods_order_30,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_rgmv_30') AS DECIMAL(18,2))      AS external_rgmv_30,
    CAST(GET_JSON_OBJECT(raw_data, '$.external_goods_order_price_30') AS DECIMAL(18,2)) AS external_goods_order_price_30,
    GETDATE() AS etl_time,
    project_id
FROM ods_xhs_creative_report_hi
WHERE ds = '${bizdate}'
;
